.TH gTranscribe "1" "Feb 24, 2016"
.SH NAME
gtranscribe \- GTK+ tool to transcribe audio files
.SH SYNOPSIS
\fBgtranscribe\fP [\-v|\-\-verbose] [image\-file]
.SH DESCRIPTION
\fBgTranscribe\fP is a simple GTK+ tool to transcribe audio files and other
sources. The playback speed can be adjusted without changing the pitch of the
voice. It supports spell checking and resuming at the last transcribed
position.
.SH OPTIONS
.TP
.BR \-v ", " \-\-verbose
Show debug messages.
.SH AUTHOR
This manual page was written by Philip Rinn <rinni@inventati.org>.
